## Operations

Arithmetic operations on NumPy arrays are applied element wise, and returns a 'NEW' array with results.


In [ ]:
import numpy as np

a = np.array([10,20,30,40])
b = a + 1
print(a)
print(b)

c = b - a
print(c)

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])

z = x @ y
print(z)

Some short hand operations like `*=` , `+=` modify the source array in place rather than creating a new one


In [11]:
a_ones = np.ones((2,3))
print(a_ones)

a_ones += 1
print(a_ones)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]


In [13]:
scores = np.array([50,45,30,49,62])
results = scores > 35

print("Pass / Faile ? :", results)
print("Centum", scores == 0)


Pass / Faile ? : [ True  True False  True  True]
Centum [False False False False False]
